[workspace]
members = [
    "crates/oil_lex",
    "crates/oil_ast",
    "crates/oil_common",
    "crates/oil_parse",
    "crates/oil",
    "crates/oil_untyped_ir",
    "crates/oil_typed_ir", "crates/oil_analyze", "crates/oil_gen",
]
resolver = "3"
