[workspace]
members = [
    "crates/oil_lex",
    "crates/oil_parse",
    "crates/oil_ast",
    "crates/oil_gen",
    "crates/oil_analyze",
    "crates/oil_cli",
    "crates/oil_common",
    "crates/oil",
    "crates/fuel",
]
resolver = "3"
