[package]
name = "oil"
version = "0.1.0"
edition = "2024"

[dependencies]
oil_common = { path = "../oil_common" }
oil_lex = { path = "../oil_lex" }
oil_ast = { path = "../oil_ast" }
fuel = { path = "../fuel" }
oil_parse = { path = "../oil_parse" }
oil_analyze = { path = "../oil_analyze" }
oil_gen = { path = "../oil_gen" }
